### ISSUE TITLE
Button fitting

### ISSUE THREAD

**Issue by KevinMehrabi** [StableTechnologies/TEZEX#100]
Our button should fit the frame elegantly. The curves should match each other. There should be the same margin not just on all sides, but continuously. Pay close attention to the corners as well. The corners need to match. 
  
Right
![image](https://user-images.githubusercontent.com/4044328/132254948-65965554-ce57-4bb7-a0fb-3f6682787cd4.jpeg)

Wrong
![image](https://user-images.githubusercontent.com/4044328/132254924-7ccef80c-7b9c-48d9-b90c-3748fec2f3d1.jpeg)

**Comment by vgaudis** [comment]
Additional exemples: 

![Screenshot 2022-12-02 at 2 28 05 PM](https://user-images.githubusercontent.com/84809270/205371028-cf174481-7986-4e51-b6ad-e85951c34ffa.png)
![Screenshot 2022-12-02 at 2 27 52 PM](https://user-images.githubusercontent.com/84809270/205371029-f38c3bda-51f5-4f3c-ade3-d464b009a158.png)
