### ISSUE TITLE
Metadata/images

### ISSUE THREAD

**Issue by KevinMehrabi** [StableTechnologies/TEZEX#173]
Attached is the favicon 
[favicon.ico.zip](https://github.com/StableTechnologies/TEZEX/files/13444440/favicon.ico.zip)

Title: TEZEX | Tezos Liquidity Exchange

Description: TEZEX (Tezos Exchange) is liquidity hub for the Tezos blockchain ecosystem — aggregating the largest liquidity sources in Tezos — trade and provide liquidity

Keywords: Tezos, tez, xtz, btc, liquidity baking, sirius, sirs, stablecoin, liquidity, exchange, dex, decentralized exchange, defi

Attached also is the meta image. 
[tezex_image.png.zip](https://github.com/StableTechnologies/TEZEX/files/13444625/tezex_image.png.zip)

Use Open Graph standard for the meta data and meta image https://ogp.me

**Comment by SiddharthV1** [comment]
@KevinMehrabi  : The only way we can use the keywords is by utilizing  them in  a sentence or two in the description, The Open Graph standard standard itself does not accept just keywords
