### ISSUE TITLE
Add multiple Swaps on TEZEX

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#52]
Add the following swaps: 
- USDT-USDtz (USDtz-USDT)
- BTC/BTCtz (BTCtz-BTC) - old Tezex #38 
- tzBTC/XTZ (XTZ/tzBTC)
- tzBTC/BTCtz (BTCtz/tzBTC)
- tzBTC/USDtz (USDtz/tzBTC)
- tzBTC/ETHtz (ETHtz/tzBTC)

**Comment by vgaudis** [comment]
Created separate ticket #79 for tzBTC/BTCtz (BTCtz/tzBTC)

**Comment by KevinMehrabi** [comment]
wUSDC-USDtz
wBUSD-USDtz
wWBTC-USDtz
