### ISSUE TITLE
Create a separate repo for bots

### ISSUE THREAD

**Issue by anonymoussprocket** [StableTechnologies/TEZEX#56]
That repo should have several sections by type of bot, for example:

- ethxtz
- xtzonly
- redeem

Move related issues to that repo as well: #17, #28.

**Comment by KevinMehrabi** [comment]
Should have clear instructions for changemakers to install and update their bots. full list of dependencies and how to get them. Screenshots, examples.

**Comment by KevinMehrabi** [comment]
Let's move this up priority-wise @vgaudis @gdsoumya

**Comment by vgaudis** [comment]
Repo created.
