### ISSUE TITLE
RC1 feedback set 1

### ISSUE THREAD

**Issue by anonymoussprocket** [StableTechnologies/TEZEX#57]
- [x] The check mark animation for the confirmation shouldn’t loop. Only play it once. [I think in the Lottie animations it’s set to loop as a default state so we need to set it to loop = false]
- [x] In the designs I specified showing only the hour minutes for when a swap will time out. If we show a timestamp anywhere that includes a date, change the text from “Swap will timeout in” to “Swap Timeout” -> [updated only thr text to Swap Timeout”]
- [x] When changing the token type, the wallet balance disappears
- [x] If the user needs to connect their wallet, the large CTA button should indicate the wallet that needs to be connected.
- [x] The minimum expected is good to show.

**Comment by vgaudis** [comment]
Remove one item and created #66.
Please create a PR for all other items fixed.

**Comment by vgaudis** [comment]
@Aeesh , please confirm that these items were already merged and deployed in a PR for #62 that way I can close this ticket.
