### ISSUE TITLE
Inaccurate Token progress model display

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#66]
The token progress model should only show the names of the 3 steps when initiated at first and as the user approves the transactions and the swap progresses it should give feedback with the checkmarks and text.

(Last unsolved item of #57)

**Comment by navi-arneja** [comment]
Here is the clickable prototype for this flow that shows the animation: https://www.figma.com/proto/PDSTzKx3Ljs4JNWbhMhye3/Tezex?node-id=542%3A13973&scaling=min-zoom&page-id=109%3A0&starting-point-node-id=542%3A13973&show-proto-sidebar=1
