### ISSUE TITLE
Stats Table Content redesign

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#75]
The new design Stats table should show liquidity by currency pairs first and then tokens.

See for example quipuswap stats (but tokens is displayed first and add half of all Liquidity pools each token is part of - for Tezex it will be the sum of each liquidity brought by changemakers for a given token)
-> https://analytics.quipuswap.com/overview

**Comment by KevinMehrabi** [comment]
See the Figma board. A specific design was created for this already.
