### ISSUE TITLE
Display the Balance to show all decimal places.

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#77]
Display the Balance to show 5 decimal places.
This will be needed when we add assets which are worth a lot like wbtc/tzbtc.
And make sure that the "not enough funds" message is adjusted appropriately.

**Comment by KevinMehrabi** [comment]
It should show all decimal places for a token. ETH and ETHtz for example are 18 decimal places

**Comment by KevinMehrabi** [comment]
however that doesn't mean show extra decimal places where there are none. if it's 6 decimal places as is the case for USDC and USDtz, then that's what it should show as. 18 if it's ETH ETHtz, so on and so forth.
