### ISSUE TITLE
Display Max Swap Limit + add check if user tries to beyond the available quantity

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#78]
Put back the max swap limit in the Ui like it was before and also put a check if user tries to go beyond that available liquidity.

**Comment by vgaudis** [comment]
Here is a more detailed description of the issue from a user feedback.
Currently on Tezex, User Bob will get a message (insufficient funds) if he enters an amount of tokens to swap > to the amount available in his wallet. 
However if Bob wants to swap an amount of tokens < to his wallet amount but > to the liquidity made available by Change-maker Nancy then a different error message should show and let him know that there is not enough liquidity for the swap to go through.
The check to implement to detect this situation is "useMax(min(userBalance, availableLiquidity))"

@gdsoumya, feel free to adjust if I missed anything.

**Comment by vgaudis** [comment]
User story: As a user wanting to convert my total balance of an asset into another token, I would like the ability to easily input the maximum amount from my wallet with a “use max” button so I don’t have to calculate and enter in an approximation leaving me with fractions of the asset.

Steps

Select an input token
Select an output token
Click on “use max”
Input field is populated with the maximum balance they are able to exchange
If the max balance exceeds the liquidity, the swap button should be disabled and display an error message: There currently isn’t enough liquidity available for this swap. Please enter an amount below [available liquidity]

**Comment by KevinMehrabi** [comment]
This error message should be moved to under the receivable amount. In this case, beneath ETHtz. 

Otherwise, it implies that the insufficient liquidity is on the sending side. Which is not the case.     

![image](https://user-images.githubusercontent.com/4044328/131262290-33d5509d-e42c-4623-976f-c0f7d1992dcc.jpeg)
