### ISSUE TITLE
Add Swap wBTC/tzBTC (tzBTC/wBTC)

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#79]

**Comment by KevinMehrabi** [comment]
- [ ]  wBTC/tzBTC (tzBTC/wBTC)
- [ ]  wBTC/BTCtz (tzBTC/BTCtz)
- [ ]  BTCtz/tzBTC (tzBTC/wBTC)

**Comment by vgaudis** [comment]
Deployed on Aug 25th.
Other 2 Swaps addition request split in new tickets #90 and #91
