### ISSUE TITLE
Add Swap WBTC/BTCtz (WBTC/BTCtz)

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#90]

**Comment by KevinMehrabi** [comment]
title confused, this new title is the actual need

**Comment by KevinMehrabi** [comment]
BTCtz contract KT1Mg7Jaxz9n6YM9XjbDLhAjbuWa9bzhAAy9

**Comment by vgaudis** [comment]
Deployed on October 1st.
